// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyLeave.Infrastructure.Persistence;

#nullable disable

namespace SkyLeave.Infrastructure.Migrations
{
    [DbContext(typeof(SkyLeaveDbContext))]
    [Migration("20250726185659_mymigrations")]
    partial class mymigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyLeave.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1111,
                            Days = 0,
                            EmployeeId = "",
                            EmployeeName = "Alice Johnson",
                            EndDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaveType = "Vacation",
                            StartDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2111,
                            Days = 0,
                            EmployeeId = "",
                            EmployeeName = "Bob Smith",
                            EndDate = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaveType = "Medical Leave",
                            StartDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Approved"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
